### ISSUE TITLE
destination names don't match between readme and consumer in message-listener-adapter

### ISSUE THREAD

**Issue by Thinkerinhell** [bsnyder/spring-jms-examples#5]
README suggests to run by command:

#### Run the Producer for the `MessageListenerAdapter` Example ####
This example requires a couple of arguments, the first one for the
destination name and the second one for the message type. The destination name
should be either FOO.TEST or FOO.TEST2. The message type should text, bytes,
map or object. Below is an example of text: 

    $ cd ./async/message-listener
    $ mvn -Pproducer exec:java -Dexec.args="FOO.TEST2 text"

but the actually destination defined in consumer xml are

    <jms:listener destination="TEST.FOO" ref="messageDelegate" />
    <jms:listener destination="TEST.FOO2" ref="messageDelegate" />

PS: the cd <PATH> above is also incorrect .
shall be $ cd ./async/message-listener-adapter

**Comment by bsnyder** [comment]
I'm sorry for replying so late. I fixed the README finally. Thank you for pointing out my typo.
